CREATE TABLE IF NOT EXISTS users (
    login VARCHAR(100) PRIMARY KEY,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS notes (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
login VARCHAR(100) NOT NULL,
title VARCHAR(100) NOT NULL,
content VARCHAR(1000) NOT NULL,
FOREIGN KEY (login) REFERENCES users(login) ON DELETE CASCADE
);